
USE RiskRaw   ;

Declare @valuationDate Date;
Set @valuationDate = '?';

SELECT 
	POS1.MARKET_VALUE_ACCRUED_INTEREST_BASE_NAV,
	pos1.MARKET_VALUE_ACCRUED_INTEREST_LOCAL,
	pos1.LOCAL_CURRENCY_CODE,
	S1.INSTRUMENT_TYPE_CODE,
	S1.SHORT_NAME,
	S1.EDM_INSTRUMENT_ID,
	PORTFOLIO_CALCULATION,
	S1.SCD_SEC_ID,
	S1.IPS_SECURITY_ID,
	POS1.LOWEST_LEVEL_PORTFOLIO,
	pos1.SUB_PORTFOLIO_CODE

FROM rpt_SCD.[Master_FN_POSITION] POS1
              LEFT JOIN rpt_SCD.[Master_FN_INSTRUMENT_CONSOLIDATED] S1 ON POS1.[EDM_INSTRUMENT_ID] = S1.[EDM_INSTRUMENT_ID]
                        WHERE 
						--POS1.LOWEST_LEVEL_PORTFOLIO IN ('GPF_ABS' , 'E0E0225')
      --                  AND 
                        POS1.EFFECTIVE_DATE = @valuationDate
                        AND POS1.SOURCE = 'SCD_MAIN'
                        AND INSTRUMENT_TYPE_CODE NOT IN ('ALM', 'CASH', 'FX_FWD','FX_SWP','FX_SPOT','MMKT_POOL_FUND','EQY_POOL_FUND','EQY_IDX_SWP','EQY_SINGLE_NAME_SWP')
                        AND POS1.PORTFOLIO_CALCULATION = 'DWH_IBOR'
						AND S1.SCD_SEC_ID = 'EBAYVIEW';

