SELECT *
FROM [RMRepository].[rmstg].[RmLiquidDerivativeOutput] 
WHERE ISR_streamName 
IN ( 
	'SCD_EBS',
	'SCD_EQUITYOPTION',
	'SCD_EIS',
	'SCD_FUT',
	'SCD_FXFWD',
	'SCD_IRS',
	'SCD_LIQUIDS',
	'SCD_FXOPTION',
	'UNIT_REALLOCATION',
	'UNITIZED_FUND'
	)
AND ParentPortfolioCode LIKE '%HG_%'
AND ParentPortfolioCode NOT IN ('EBRONCO','E0071N','ME0017','ME0044','ME0358','E0074','ME0025','ME173B','ME170D','ME170SIN','ME170UIN')