SELECT *
FROM [RMRepository].[rmstg].[RmLiquidDerivativeOutput] 
WHERE HoldingGroupName NOT IN ('E0040', 'E0041','E0042','E0043','E0080','E0084','RISKPE01','RISKIN01','RISKRR01','E0044')
AND ISR_streamName 
IN ( 
	'SCD_EBS',
	'SCD_EQUITYOPTION',
	'SCD_FUT',
	'SCD_EIS',
	'SCD_FXFWD',
	'SCD_IRS',
	'SCD_LIQUIDS',
	'UNIT_REALLOCATION',
	'UNITIZED_FUND'
	)
AND ParentPortfolioCode NOT LIKE '%HG_%'