SELECT [EFFECTIVE_DATE]
,[CURRENCY_CODE]
,[CAD_QUOTE_PAIR]
,[IPS_CAD_QUOTE_MID] -----USE THIS VALUE (IN SCALE CALCULATION)
,[USD_CONVENTION_PAIR]
,[USD_CONVENTION_MID]
,[USD_BASE_PAIR]
,[USD_BASE_MID]

FROM [RiskRaw].[INFO_SERVICE].[VW_MASTER_FX_RATE_V1]
where EFFECTIVE_DATE = ?
and CURRENCY_CODE = 'USD'